version: '3'

services:
  db:
    image: postgres:alpine
    ports:
      - "15432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql
  app:
    build: .
    entrypoint: /opt/entrypoint.sh
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.docker
      - RABBITMQ_HOST=queue
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    volumes:
      - ./cloudigrade:/opt/cloudigrade:Z
      - ./docker/entrypoint.sh:/opt/entrypoint.sh:Z
      - /tmp/cloudigrade/socket:/var/run/cloudigrade:Z
      - /tmp/cloudigrade/static:/srv/cloudigrade/static:Z
    depends_on:
      - db
  web:
    image: nginx:alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:Z
      - /tmp/cloudigrade/socket:/var/run/cloudigrade:Z
      - /tmp/cloudigrade/static:/srv/cloudigrade/static:Z
    ports:
      - "8080:8080"
    depends_on:
      - app
  queue:
    image: rabbitmq:management-alpine
    hostname: cloudiqueue
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DISK_FREE_LIMIT={mem_relative, 1.5}
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
