version: '3'

services:
  db:
    image: postgres:alpine
    ports:
      - "15432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql
  app:
    build: .
    entrypoint: /opt/cloudigrade/entrypoint.sh
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.docker
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    volumes:
      - ./cloudigrade:/opt/cloudigrade
      - ./docker/entrypoint.sh:/opt/cloudigrade/entrypoint.sh
      - /tmp/cloudigrade/socket:/var/run/cloudigrade
      - static:/opt/cloudigrade/static
    depends_on:
      - db
  web:
    image: nginx:alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - /tmp/cloudigrade/socket:/var/run/cloudigrade
      - static:/opt/cloudigrade/static
    ports:
      - "8000:80"
    depends_on:
      - app
  queue:
    image: rabbitmq:alpine
    hostname: cloudiqueue
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=cloudigrade
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_DISK_FREE_LIMIT={mem_relative, 1.5}
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
volumes:
  static:
