[tool.poetry]
name = "cloudigrade"
version = "1.0.0"
description = "Cloudigrade is an open-source suite of tools for tracking Linux distribution use in public cloud platforms."
authors = ["Cloudigrade Dev Team <doppler-dev@redhat.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.8"
django-environ = "~=0.4.5"
boto3 = "~=1.12.0"
botocore = "~=1.15.0"
celery = "~=4.4.0"
django-model-utils = "~=4.0.0"
jsonpickle = "~=1.3"
psycopg2-binary = "~=2.8.4"
python-dateutil = "~=2.8.0"
djangorestframework = "~=3.12.2"
drf-insights-pagination = "~=1.0.0"
gunicorn = "~=20.0.4"
django-health-check = "~=3.11.1"
sentry-sdk = "~=0.19.4"
tqdm = "~=4.42.1"
Django = "~=3.0.0"
django_celery_beat = "~=1.5.0"
Faker = "~=4.0.1"
python-daemon = "~=2.2.4"
requests = "~=2.22.0"
uritemplate = "~=3.0.0"
rest-framework-generic-relations = "~=2.0.0"
pycurl = "~=7.43.0"
watchtower = "~=0.8.0"
confluent-kafka = "^1.5.0"
django-prometheus = "^2.1.0"
django-filter = "~=2.4.0"

[tool.poetry.dev-dependencies]
seqdiag = "*"
jinja2 = "*"
flake8 = "*"
flake8-docstrings = "*"
flake8-import-order = "*"
isort = "*"
coverage = "*"
tblib = "*"
pydocstyle = "*"
flake8-black = "*"
black = {version = "*", allow-prereleases = true}
openapi-spec-validator = "^0.2.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
