[tool.poetry]
name = "cloudigrade"
version = "1.0.0"
description = "Cloudigrade is an open-source suite of tools for tracking Linux distribution use in public cloud platforms."
authors = ["Cloudigrade Dev Team <doppler-dev@redhat.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.9"
ansible = "~=4.2.0"
boto = "~=2.49.0"
django-environ = "~=0.8.1"
boto3 = "~=1.20.37"
celery = "~=5.2.2"
django-model-utils = "~=4.2.0"
jsonpickle = "~=2.0"
psycopg2 = "~=2.9.3"
python-dateutil = "~=2.8.1"
djangorestframework = "~=3.13.1"
drf-insights-pagination = "~=1.0.1"
gunicorn = "~=20.1.0"
django-health-check = "~=3.16.5"
sentry-sdk = "~=1.5.2"
tqdm = "~=4.62.3"
Django = "~=3.2.11"
django_celery_beat = "~=2.2.1"
Faker = "~=11.3.0"
requests = "~=2.27.1"
uritemplate = "~=4.1.1"
rest-framework-generic-relations = "~=2.0.0"
watchtower = "~=1.0.6"
confluent-kafka = "^1.6.1"
django-filter = "~=21.1"
django-cache-memoize = "~=0.1.9"
azure-mgmt-compute = "^21.0.0"
azure-identity = "^1.6.0"
bitmath = "^1.3.3"
app-common-python = "^0.1.8"
azure-mgmt-resourcegraph = "^8.0.0"
azure-mgmt-resource = "^19.0.0"
azure-cli-core = "^2.27.2"
django-prometheus = "~=2.1.0"
redis = "^4.1.0"


[tool.poetry.dev-dependencies]
jinja2 = "*"
flake8 = "*"
flake8-docstrings = "*"
flake8-import-order = "*"
isort = "*"
coverage = "*"
pydocstyle = "*"
flake8-black = "*"
black = {version = "*", allow-prereleases = true}
openapi-spec-validator = "^0.3.1"
jupyter = "^1.0.0"
ipython = "^7.24.1"
django-extensions = "^3.1.3"
crc-bonfire = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
